import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import AppProvider from "@/redux/provider/AppProvider";
import { ServerDecrypt } from "@/helper/server";
import { cookies } from "next/headers";
import Auth from "@/components/Auth/Auth";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("accessToken");
  const response = await ServerDecrypt();

  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <AppProvider>
          <Auth response={response} />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
