export const countries = [
  { value: "", label: "" },
  { value: "AFG", label: "Afghanistan" },
  { value: "ALB", label: "Albania" },
  { value: "DZA", label: "Algeria" },
  { value: "ASM", label: "American Samoa" },
  { value: "AND", label: "Andorra" },
  { value: "AGO", label: "Angola" },
  { value: "AIA", label: "Anguilla" },
  { value: "ATA", label: "Antarctica" },
  { value: "ATG", label: "Antigua and Barbuda" },
  { value: "ARG", label: "Argentina" },
  { value: "ARM", label: "Armenia" },
  { value: "ABW", label: "Aruba" },
  { value: "AUS", label: "Australia" },
  { value: "AUT", label: "Austria" },
  { value: "AZE", label: "Azerbaijan" },
  { value: "BHS", label: "Bahamas" },
  { value: "BHR", label: "Bahrain" },
  { value: "BGD", label: "Bangladesh" },
  { value: "BRB", label: "Barbados" },
  { value: "BLR", label: "Belarus" },
  { value: "BEL", label: "Belgium" },
  { value: "BLZ", label: "Belize" },
  { value: "BEN", label: "Benin" },
  { value: "BMU", label: "Bermuda" },
  { value: "BTN", label: "Bhutan" },
  { value: "BOL", label: "Bolivia" },
  { value: "BES", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "BIH", label: "Bosnia and Herzegovina" },
  { value: "BWA", label: "Botswana" },
  { value: "BVT", label: "Bouvet Island" },
  { value: "BRA", label: "Brazil" },
  { value: "IOT", label: "British Indian Ocean Territory" },
  { value: "BRN", label: "Brunei Darussalam" },
  { value: "BGR", label: "Bulgaria" },
  { value: "BFA", label: "Burkina Faso" },
  { value: "BDI", label: "Burundi" },
  { value: "KHM", label: "Cambodia" },
  { value: "CMR", label: "Cameroon" },
  { value: "CAN", label: "Canada" },
  { value: "CPV", label: "Cabo Verde" },
  { value: "CYM", label: "Cayman Islands" },
  { value: "CAF", label: "Central African Republic" },
  { value: "TCD", label: "Chad" },
  { value: "CHL", label: "Chile" },
  { value: "CHN", label: "China" },
  { value: "CXR", label: "Christmas Island" },
  { value: "CCK", label: "Cocos (Keeling) Islands" },
  { value: "COL", label: "Colombia" },
  { value: "COM", label: "Comoros" },
  { value: "COG", label: "Congo" },
  { value: "COD", label: "Congo, Democratic Republic of the" },
  { value: "COK", label: "Cook Islands" },
  { value: "CRI", label: "Costa Rica" },
  { value: "CIV", label: "Côte d'Ivoire" },
  { value: "HRV", label: "Croatia" },
  { value: "CUB", label: "Cuba" },
  { value: "CUW", label: "Curaçao" },
  { value: "CYP", label: "Cyprus" },
  { value: "CZE", label: "Czechia" },
  { value: "DNK", label: "Denmark" },
  { value: "DJI", label: "Djibouti" },
  { value: "DMA", label: "Dominica" },
  { value: "DOM", label: "Dominican Republic" },
  { value: "ECU", label: "Ecuador" },
  { value: "EGY", label: "Egypt" },
  { value: "SLV", label: "El Salvador" },
  { value: "GNQ", label: "Equatorial Guinea" },
  { value: "ERI", label: "Eritrea" },
  { value: "EST", label: "Estonia" },
  { value: "SWZ", label: "Eswatini" },
  { value: "ETH", label: "Ethiopia" },
  { value: "FLK", label: "Falkland Islands (Malvinas)" },
  { value: "FRO", label: "Faroe Islands" },
  { value: "FJI", label: "Fiji" },
  { value: "FIN", label: "Finland" },
  { value: "FRA", label: "France" },
  { value: "GUF", label: "French Guiana" },
  { value: "PYF", label: "French Polynesia" },
  { value: "ATF", label: "French Southern Territories" },
  { value: "GAB", label: "Gabon" },
  { value: "GMB", label: "Gambia" },
  { value: "GEO", label: "Georgia" },
  { value: "DEU", label: "Germany" },
  { value: "GHA", label: "Ghana" },
  { value: "GIB", label: "Gibraltar" },
  { value: "GRC", label: "Greece" },
  { value: "GRL", label: "Greenland" },
  { value: "GRD", label: "Grenada" },
  { value: "GLP", label: "Guadeloupe" },
  { value: "GUM", label: "Guam" },
  { value: "GTM", label: "Guatemala" },
  { value: "GGY", label: "Guernsey" },
  { value: "GIN", label: "Guinea" },
  { value: "GNB", label: "Guinea-Bissau" },
  { value: "GUY", label: "Guyana" },
  { value: "HTI", label: "Haiti" },
  { value: "HMD", label: "Heard Island and McDonald Islands" },
  { value: "VAT", label: "Holy See" },
  { value: "HND", label: "Honduras" },
  { value: "HKG", label: "Hong Kong" },
  { value: "HUN", label: "Hungary" },
  { value: "ISL", label: "Iceland" },
  { value: "IND", label: "India" },
  { value: "IDN", label: "Indonesia" },
  { value: "IRN", label: "Iran (Islamic Republic of)" },
  { value: "IRQ", label: "Iraq" },
  { value: "IRL", label: "Ireland" },
  { value: "IMN", label: "Isle of Man" },
  { value: "ISR", label: "Israel" },
  { value: "ITA", label: "Italy" },
  { value: "JAM", label: "Jamaica" },
  { value: "JPN", label: "Japan" },
  { value: "JEY", label: "Jersey" },
  { value: "JOR", label: "Jordan" },
  { value: "KAZ", label: "Kazakhstan" },
  { value: "KEN", label: "Kenya" },
  { value: "KIR", label: "Kiribati" },
  { value: "PRK", label: "Korea (Democratic People's Republic of)" },
  { value: "KOR", label: "Korea, Republic of" },
  { value: "KWT", label: "Kuwait" },
  { value: "KGZ", label: "Kyrgyzstan" },
  { value: "LAO", label: "Lao People's Democratic Republic" },
  { value: "LVA", label: "Latvia" },
  { value: "LBN", label: "Lebanon" },
  { value: "LSO", label: "Lesotho" },
  { value: "LBR", label: "Liberia" },
  { value: "LBY", label: "Libya" },
  { value: "LIE", label: "Liechtenstein" },
  { value: "LTU", label: "Lithuania" },
  { value: "LUX", label: "Luxembourg" },
  { value: "MAC", label: "Macao" },
  { value: "MDG", label: "Madagascar" },
  { value: "MWI", label: "Malawi" },
  { value: "MYS", label: "Malaysia" },
  { value: "MDV", label: "Maldives" },
  { value: "MLI", label: "Mali" },
  { value: "MLT", label: "Malta" },
  { value: "MHL", label: "Marshall Islands" },
  { value: "MTQ", label: "Martinique" },
  { value: "MRT", label: "Mauritania" },
  { value: "MUS", label: "Mauritius" },
  { value: "MYT", label: "Mayotte" },
  { value: "MEX", label: "Mexico" },
  { value: "FSM", label: "Micronesia (Federated States of)" },
  { value: "MDA", label: "Moldova, Republic of" },
  { value: "MCO", label: "Monaco" },
  { value: "MNG", label: "Mongolia" },
  { value: "MNE", label: "Montenegro" },
  { value: "MSR", label: "Montserrat" },
  { value: "MAR", label: "Morocco" },
  { value: "MOZ", label: "Mozambique" },
  { value: "MMR", label: "Myanmar" },
  { value: "NAM", label: "Namibia" },
  { value: "NRU", label: "Nauru" },
  { value: "NPL", label: "Nepal" },
  { value: "NLD", label: "Netherlands" },
  { value: "NCL", label: "New Caledonia" },
  { value: "NZL", label: "New Zealand" },
  { value: "NIC", label: "Nicaragua" },
  { value: "NER", label: "Niger" },
  { value: "NGA", label: "Nigeria" },
  { value: "NIU", label: "Niue" },
  { value: "NFK", label: "Norfolk Island" },
  { value: "MKD", label: "North Macedonia" },
  { value: "MNP", label: "Northern Mariana Islands" },
  { value: "NOR", label: "Norway" },
  { value: "OMN", label: "Oman" },
  { value: "PAK", label: "Pakistan" },
  { value: "PLW", label: "Palau" },
  { value: "PSE", label: "Palestine, State of" },
  { value: "PAN", label: "Panama" },
  { value: "PNG", label: "Papua New Guinea" },
  { value: "PRY", label: "Paraguay" },
  { value: "PER", label: "Peru" },
  { value: "PHL", label: "Philippines" },
  { value: "PCN", label: "Pitcairn" },
  { value: "POL", label: "Poland" },
  { value: "PRT", label: "Portugal" },
  { value: "PRI", label: "Puerto Rico" },
  { value: "QAT", label: "Qatar" },
  { value: "REU", label: "Réunion" },
  { value: "ROU", label: "Romania" },
  { value: "RUS", label: "Russian Federation" },
  { value: "RWA", label: "Rwanda" },
  { value: "BLM", label: "Saint Barthélemy" },
  { value: "SHN", label: "Saint Helena, Ascension and Tristan da Cunha" },
  { value: "KNA", label: "Saint Kitts and Nevis" },
  { value: "LCA", label: "Saint Lucia" },
  { value: "MAF", label: "Saint Martin (French part)" },
  { value: "SPM", label: "Saint Pierre and Miquelon" },
  { value: "VCT", label: "Saint Vincent and the Grenadines" },
  { value: "WSM", label: "Samoa" },
  { value: "SMR", label: "San Marino" },
  { value: "STP", label: "Sao Tome and Principe" },
  { value: "SAU", label: "Saudi Arabia" },
  { value: "SEN", label: "Senegal" },
  { value: "SRB", label: "Serbia" },
  { value: "SYC", label: "Seychelles" },
  { value: "SLE", label: "Sierra Leone" },
  { value: "SGP", label: "Singapore" },
  { value: "SXM", label: "Sint Maarten (Dutch part)" },
  { value: "SVK", label: "Slovakia" },
  { value: "SVN", label: "Slovenia" },
  { value: "SLB", label: "Solomon Islands" },
  { value: "SOM", label: "Somalia" },
  { value: "ZAF", label: "South Africa" },
  { value: "SGS", label: "South Georgia and the South Sandwich Islands" },
  { value: "SSD", label: "South Sudan" },
  { value: "ESP", label: "Spain" },
  { value: "LKA", label: "Sri Lanka" },
  { value: "SDN", label: "Sudan" },
  { value: "SUR", label: "Suriname" },
  { value: "SJM", label: "Svalbard and Jan Mayen" },
  { value: "SWE", label: "Sweden" },
  { value: "CHE", label: "Switzerland" },
  { value: "SYR", label: "Syrian Arab Republic" },
  { value: "TWN", label: "Taiwan, Province of China" },
  { value: "TJK", label: "Tajikistan" },
  { value: "TZA", label: "Tanzania, United Republic of" },
  { value: "THA", label: "Thailand" },
  { value: "TLS", label: "Timor-Leste" },
  { value: "TGO", label: "Togo" },
  { value: "TKL", label: "Tokelau" },
  { value: "TON", label: "Tonga" },
  { value: "TTO", label: "Trinidad and Tobago" },
  { value: "TUN", label: "Tunisia" },
  { value: "TUR", label: "Turkey" },
  { value: "TKM", label: "Turkmenistan" },
  { value: "TCA", label: "Turks and Caicos Islands" },
  { value: "TUV", label: "Tuvalu" },
  { value: "UGA", label: "Uganda" },
  { value: "UKR", label: "Ukraine" },
  { value: "ARE", label: "United Arab Emirates" },
  {
    value: "GBR",
    label: "United Kingdom of Great Britain and Northern Ireland",
  },
  { value: "UMI", label: "United States Minor Outlying Islands" },
  { value: "USA", label: "United States of America" },
  { value: "URY", label: "Uruguay" },
  { value: "UZB", label: "Uzbekistan" },
  { value: "VUT", label: "Vanuatu" },
  { value: "VEN", label: "Venezuela (Bolivarian Republic of)" },
  { value: "VNM", label: "Viet Nam" },
  { value: "VGB", label: "Virgin Islands (British)" },
  { value: "VIR", label: "Virgin Islands (U.S.)" },
  { value: "WLF", label: "Wallis and Futuna" },
  { value: "ESH", label: "Western Sahara" },
  { value: "YEM", label: "Yemen" },
  { value: "ZMB", label: "Zambia" },
  { value: "ZWE", label: "Zimbabwe" },
];

export const nationalities = [
  { label: "", value: "" },
  { label: "Afghan", value: "Afghan" },
  { label: "Albanian", value: "Albanian" },
  { label: "Algerian", value: "Algerian" },
  { label: "American", value: "American" },
  { label: "Andorran", value: "Andorran" },
  { label: "Angolan", value: "Angolan" },
  { label: "Antiguans", value: "Antiguans" },
  { label: "Argentine", value: "Argentine" },
  { label: "Armenian", value: "Armenian" },
  { label: "Australian", value: "Australian" },
  { label: "Austrian", value: "Austrian" },
  { label: "Azerbaijani", value: "Azerbaijani" },
  { label: "Bahaman", value: "Bahaman" },
  { label: "Bahraini", value: "Bahraini" },
  { label: "Bangladeshi", value: "Bangladeshi" },
  { label: "Barbadian", value: "Barbadian" },
  { label: "Barbudans", value: "Barbudans" },
  { label: "Batswana", value: "Batswana" },
  { label: "Belarusian", value: "Belarusian" },
  { label: "Belgian", value: "Belgian" },
  { label: "Belizean", value: "Belizean" },
  { label: "Beninese", value: "Beninese" },
  { label: "Bhutanese", value: "Bhutanese" },
  { label: "Bolivian", value: "Bolivian" },
  { label: "Bosnian", value: "Bosnian" },
  { label: "Brazilian", value: "Brazilian" },
  { label: "British", value: "British" },
  { label: "Bruneian", value: "Bruneian" },
  { label: "Bulgarian", value: "Bulgarian" },
  { label: "Burkinabe", value: "Burkinabe" },
  { label: "Burmese", value: "Burmese" },
  { label: "Burundian", value: "Burundian" },
  { label: "Cabo Verdean", value: "Cabo Verdean" },
  { label: "Cambodian", value: "Cambodian" },
  { label: "Cameroonian", value: "Cameroonian" },
  { label: "Canadian", value: "Canadian" },
  { label: "Chadian", value: "Chadian" },
  { label: "Chilean", value: "Chilean" },
  { label: "Chinese", value: "Chinese" },
  { label: "Colombian", value: "Colombian" },
  { label: "Comoran", value: "Comoran" },
  { label: "Congolese", value: "Congolese" },
  { label: "Costa Rican", value: "Costa Rican" },
  { label: "Croatian", value: "Croatian" },
  { label: "Cuban", value: "Cuban" },
  { label: "Cypriot", value: "Cypriot" },
  { label: "Czech", value: "Czech" },
  { label: "Danish", value: "Danish" },
  { label: "Djiboutian", value: "Djiboutian" },
  { label: "Dominican", value: "Dominican" },
  { label: "Dutch", value: "Dutch" },
  { label: "East Timorese", value: "East Timorese" },
  { label: "Ecuadorian", value: "Ecuadorian" },
  { label: "Egyptian", value: "Egyptian" },
  { label: "Emirian", value: "Emirian" },
  { label: "Equatorial Guinean", value: "Equatorial Guinean" },
  { label: "Eritrean", value: "Eritrean" },
  { label: "Estonian", value: "Estonian" },
  { label: "Eswatini", value: "Eswatini" },
  { label: "Ethiopian", value: "Ethiopian" },
  { label: "Fijian", value: "Fijian" },
  { label: "Filipino", value: "Filipino" },
  { label: "Finnish", value: "Finnish" },
  { label: "French", value: "French" },
  { label: "Gabonese", value: "Gabonese" },
  { label: "Gambian", value: "Gambian" },
  { label: "Georgian", value: "Georgian" },
  { label: "German", value: "German" },
  { label: "Ghanaian", value: "Ghanaian" },
  { label: "Greek", value: "Greek" },
  { label: "Grenadian", value: "Grenadian" },
  { label: "Guatemalan", value: "Guatemalan" },
  { label: "Guinean", value: "Guinean" },
  { label: "Guyanese", value: "Guyanese" },
  { label: "Haitian", value: "Haitian" },
  { label: "Honduran", value: "Honduran" },
  { label: "Hungarian", value: "Hungarian" },
  { label: "I-Kiribati", value: "I-Kiribati" },
  { label: "Icelander", value: "Icelander" },
  { label: "Indian", value: "Indian" },
  { label: "Indonesian", value: "Indonesian" },
  { label: "Iranian", value: "Iranian" },
  { label: "Iraqi", value: "Iraqi" },
  { label: "Irish", value: "Irish" },
  { label: "Israeli", value: "Israeli" },
  { label: "Italian", value: "Italian" },
  { label: "Ivorian", value: "Ivorian" },
  { label: "Jamaican", value: "Jamaican" },
  { label: "Japanese", value: "Japanese" },
  { label: "Jordanian", value: "Jordanian" },
  { label: "Kazakhstani", value: "Kazakhstani" },
  { label: "Kenyan", value: "Kenyan" },
  { label: "Kittian and Nevisian", value: "Kittian and Nevisian" },
  { label: "Korean", value: "Korean" },
  { label: "Kuwaiti", value: "Kuwaiti" },
  { label: "Kyrgyz", value: "Kyrgyz" },
  { label: "Laotian", value: "Laotian" },
  { label: "Latvian", value: "Latvian" },
  { label: "Lebanese", value: "Lebanese" },
  { label: "Lesotho", value: "Lesotho" },
  { label: "Liberian", value: "Liberian" },
  { label: "Libyan", value: "Libyan" },
  { label: "Liechtensteiner", value: "Liechtensteiner" },
  { label: "Lithuanian", value: "Lithuanian" },
  { label: "Luxembourger", value: "Luxembourger" },
  { label: "Macanese", value: "Macanese" },
  { label: "Macedonian", value: "Macedonian" },
  { label: "Malagasy", value: "Malagasy" },
  { label: "Malawian", value: "Malawian" },
  { label: "Malaysian", value: "Malaysian" },
  { label: "Maldivian", value: "Maldivian" },
  { label: "Malian", value: "Malian" },
  { label: "Malta", value: "Malta" },
  { label: "Marshallese", value: "Marshallese" },
  { label: "Mauritanian", value: "Mauritanian" },
  { label: "Mauritian", value: "Mauritian" },
  { label: "Mexican", value: "Mexican" },
  { label: "Micronesian", value: "Micronesian" },
  { label: "Moldovan", value: "Moldovan" },
  { label: "Monacan", value: "Monacan" },
  { label: "Mongolian", value: "Mongolian" },
  { label: "Moroccan", value: "Moroccan" },
  { label: "Mozambican", value: "Mozambican" },
  { label: "Namibian", value: "Namibian" },
  { label: "Nauruan", value: "Nauruan" },
  { label: "Nepalese", value: "Nepalese" },
  { label: "New Zealander", value: "New Zealander" },
  { label: "Nicaraguan", value: "Nicaraguan" },
  { label: "Nigerian", value: "Nigerian" },
  { label: "Nigerien", value: "Nigerien" },
  { label: "North Korean", value: "North Korean" },
  { label: "North Macedonian", value: "North Macedonian" },
  { label: "Norwegian", value: "Norwegian" },
  { label: "Omani", value: "Omani" },
  { label: "Pakistani", value: "Pakistani" },
  { label: "Palauan", value: "Palauan" },
  { label: "Panamanian", value: "Panamanian" },
  { label: "Papua New Guinean", value: "Papua New Guinean" },
  { label: "Paraguayan", value: "Paraguayan" },
  { label: "Peruvian", value: "Peruvian" },
  { label: "Philippine", value: "Philippine" },
  { label: "Polish", value: "Polish" },
  { label: "Portuguese", value: "Portuguese" },
  { label: "Qatari", value: "Qatari" },
  { label: "Romanian", value: "Romanian" },
  { label: "Russian", value: "Russian" },
  { label: "Rwandan", value: "Rwandan" },
  { label: "Saint Lucian", value: "Saint Lucian" },
  { label: "Salvadoran", value: "Salvadoran" },
  { label: "Samoan", value: "Samoan" },
  { label: "San Marinese", value: "San Marinese" },
  { label: "Sao Tomean", value: "Sao Tomean" },
  { label: "Saudi Arabian", value: "Saudi Arabian" },
  { label: "Senegalese", value: "Senegalese" },
  { label: "Serbian", value: "Serbian" },
  { label: "Seychellois", value: "Seychellois" },
  { label: "Sierra Leonean", value: "Sierra Leonean" },
  { label: "Singaporean", value: "Singaporean" },
  { label: "Slovak", value: "Slovak" },
  { label: "Slovenian", value: "Slovenian" },
  { label: "Solomon Islander", value: "Solomon Islander" },
  { label: "Somali", value: "Somali" },
  { label: "South African", value: "South African" },
  { label: "South Sudanese", value: "South Sudanese" },
  { label: "Spanish", value: "Spanish" },
  { label: "Sri Lankan", value: "Sri Lankan" },
  { label: "Sudanese", value: "Sudanese" },
  { label: "Surinamese", value: "Surinamese" },
  { label: "Swazi", value: "Swazi" },
  { label: "Swedish", value: "Swedish" },
  { label: "Swiss", value: "Swiss" },
  { label: "Syrian", value: "Syrian" },
  { label: "Taiwanese", value: "Taiwanese" },
  { label: "Tajik", value: "Tajik" },
  { label: "Tanzanian", value: "Tanzanian" },
  { label: "Thai", value: "Thai" },
  { label: "Togolese", value: "Togolese" },
  { label: "Tongan", value: "Tongan" },
  { label: "Trinidadian and Tobagonian", value: "Trinidadian and Tobagonian" },
  { label: "Tunisian", value: "Tunisian" },
  { label: "Turkish", value: "Turkish" },
  { label: "Turkmen", value: "Turkmen" },
  { label: "Tuvaluan", value: "Tuvaluan" },
  { label: "Ugandan", value: "Ugandan" },
  { label: "Ukrainian", value: "Ukrainian" },
  { label: "Uruguayan", value: "Uruguayan" },
  { label: "Uzbekistani", value: "Uzbekistani" },
  { label: "Vanuatu", value: "Vanuatu" },
  { label: "Venezuelan", value: "Venezuelan" },
  { label: "Vietnamese", value: "Vietnamese" },
  { label: "Yemeni", value: "Yemeni" },
  { label: "Zambian", value: "Zambian" },
  { label: "Zimbabwean", value: "Zimbabwean" },
];

export const scope = [
  {
    label: "",
    value: "",
  },
  {
    label: "International",
    value: "international",
  },
  {
    label: "Local",
    value: "local",
  },
];

export const statusOptions = [
  {
    label: "",
    value: "",
  },
  { label: "Active", value: "active" },
  { label: "Inactive", value: "inactive" },
  { label: "Under Construction", value: "under construction" },
  { label: "Closed", value: "closed" },
];
